import type { TabId } from "./shared/ha-context";

export const TOOLS_CARD_STRINGS = {
  docs: {
    wifiCommandsUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/wifi_commands.md",
    backupUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/backup.md",
  },
  tabs: {
    cache: "Hub",
    wifiCommands: "Wifi Commands",
    wifiShort: "Wifi",
    backup: "Backup",
    settings: "Settings",
    logs: "Logs",
  },
  tabDocs: {
    wifi_commands: "Wifi Commands documentation",
    backup: "Backup documentation",
  } satisfies Partial<Record<TabId, string>>,
  backend: {
    unavailableTitle: "Backend not available",
    unavailableCopy: "Waiting for the Sofabaton X integration to finish starting...",
    versionMismatchTitle: "Refresh required to update the Sofabaton Control Panel card",
    versionMismatchCopy:
      "This dashboard is still using an older cached version of the Sofabaton Control Panel card than the one now running in Home Assistant. Refresh or reopen the dashboard/browser before using the control panel again so the updated card can load.",
    backendExpects: "Backend expects",
    cardLoaded: "Card loaded",
    unknownVersion: "unknown",
    refreshingCache: "Refreshing cache...",
    hubCommandInProgress: "Hub command in progress...",
  },
  hubUnavailable: {
    title: "Hub unavailable",
    copy: "This hub is not connected, so the control panel is unavailable until the hub reconnects.",
  },
  settings: {
    loading: "Loading...",
    noHubsFound: "No hubs found.",
    unknownHubName: "Unknown",
    activities: "Activities",
    devices: "Devices",
    persistentCacheTitle: "Persistent Cache",
    persistentCacheDescription: "Store activity and device data locally for faster access.",
    persistentCacheFooter: "GLOBAL",
    hexLoggingTitle: "Hex Logging",
    hexLoggingDescription: "Log raw hex traffic between hub, integration, and app.",
    proxyTitle: "Proxy",
    proxyDescription: "Let the official Sofabaton app share the hub connection with HA simultaneously.",
    wifiDeviceTitle: "WiFi Device",
    wifiDeviceDescription: "Enable the HTTP listener that captures remote button presses and routes them to HA actions.",
    findRemoteTitle: "Find Remote",
    findRemoteDescription: "Make the remote beep so you can locate it.",
    syncRemoteTitle: "Sync Remote",
    syncRemoteDescription: "Push the latest configuration to the physical remote.",
  },
  cache: {
    loading: "Loading...",
    noHubsFound: "No hubs found.",
    persistentCacheOffTitle: "Persistent cache is off",
    persistentCacheOffCopy:
      "Turn it on to browse cached activities and devices, and to unlock Backup workflows that depend on it.",
    enablingPersistentCache: "Enabling...",
    enablePersistentCache: "Enable persistent cache",
    devIdBadge: "DevID",
    favIdBadge: "FavID",
    comIdBadge: "ComID",
    activityFallback: (id: number) => `Activity ${id}`,
    deviceFallback: (id: number) => `Device ${id}`,
    favoriteFallback: (commandId: number) => `Favorite ${commandId}`,
    macroFallback: (commandId: number) => `Macro ${commandId}`,
    activityCounts: (favorites: number, macros: number, buttons: number) =>
      `${favorites} favs / ${macros} macros / ${buttons} btns`,
    deviceCommandCount: (count: number) => `${count} cmds`,
    favorites: "Favorites",
    macros: "Macros",
    buttons: "Buttons",
    noCachedData: "No cached data yet.",
    noCachedCommands: "No cached commands.",
    staleBanner: "Cache was updated externally. Refresh to see latest data.",
    refresh: "Refresh",
    activities: "Activities",
    devices: "Devices",
    refreshList: "Refresh list",
    refreshAll: "Refresh all",
    editActivity: "Edit activity",
    editDevice: "Edit device",
  },
  logs: {
    loading: "Loading log stream...",
    empty: "No log lines captured for this hub yet.",
    liveConsole: "Live Console",
  },
  cacheRefresh: {
    label: "Refresh all",
    running: "Refreshing…",
    starting: "Starting hub cache refresh…",
    working: "Reading your hub's configuration…",
    done: "Hub cache refreshed.",
  },
  progress: {
    homeAssistant: "Home Assistant",
    sofabatonHub: "Sofabaton Hub",
    working: "Working...",
    backupTitle: "Creating backup",
    restoreTitle: "Restoring backup",
  },
  activities: {
    loading: "Loading activities...",
    selectHub: "Select a hub to edit its activities.",
    activityFallback: (id: number) => `Activity ${id}`,
    // Guard panels (§4.1), rendered inside the editor view.
    appConnectedTitle: "The Sofabaton app is connected",
    appConnectedBody: "Close the Sofabaton app to edit the hub configuration.",
    operationRunningTitle: "Another operation is running",
    operationRunningBody: "Wait for the current backup, restore, or sync to finish, then try again.",
    // Capture flow (§4.2).
    captureTitle: "Reading your hub",
    captureMessage: "Reading your hub's configuration…",
    captureMessageWithStep: (current: number, total: number) =>
      `Reading your hub's configuration… (device ${current} of ${total})`,
    captureFailedTitle: "Couldn't read the hub",
    captureFailedBody: "The hub stopped responding before we finished reading it.",
    retry: "Retry",
    back: "Back",
    // Cache-sourced capture (blob-free structural bundle).
    capturingFromCache: (kind: "activity" | "device") => `Loading ${kind} from the hub cache…`,
    needsRefreshTitle: "Refresh the hub cache to edit",
    needsRefreshBody: (kind: "activity" | "device") =>
      `This ${kind} isn't in the local hub cache yet. Refresh the hub cache (a few seconds) to load it into the editor.`,
    // Session restore banner (§4.6).
    // Live-mode edit header (§4.3). The header mirrors the Wifi command
    // editor: a single stateful Sync button (no dirty chip, no review/discard).
    syncToHub: "Sync to Hub",
    syncUpToDate: "Up to date",
    // Immediate entity delete (executed on the hub right away).
    deletingTitle: (kind: "activity" | "device") => `Deleting ${kind}`,
    deletingMessage: (kind: "activity" | "device") => `Removing this ${kind} from the hub…`,
    // Sync flow (§4.5).
    syncingTitle: "Syncing to your hub",
    syncingMessage: "Writing your changes to the hub…",
    syncSuccess: "Synced to hub.",
    syncPlanSummary: (count: number) => `${count} hub ${count === 1 ? "write" : "writes"}`,
    syncFailedTitle: "Sync didn't finish",
    syncFailedStep: (step: string) => `The hub stopped at: ${step}`,
    syncStaleTitle: (kind: "activity" | "device") => `This ${kind} changed on the hub`,
    syncStaleBody: (kind: "activity" | "device") =>
      `The ${kind} was edited on the hub since you loaded it, so your changes can't be safely applied. Reload the hub's current version to continue — your unsaved edits will be discarded.`,
    syncRetry: "Retry sync",
    syncReload: "Reload from hub",
    syncKeepEditing: "Keep editing",
    exitUnsyncedTitle: "Unsynced changes",
    exitUnsyncedBody: (kind: "activity" | "device") =>
      `This ${kind} has changes that have not been synced to the hub. Sync them now, or leave without syncing and discard the local edit.`,
    exitSyncNow: "Sync now",
    exitWithoutSync: "Leave without syncing",
    // Dismiss label reused by the sync-success / delete-error banners.
    discardConfirmCancel: "Keep editing",
    // Review-list section titles + entry templates (activity-diff.ts).
    review: {
      sectionDevices: "Devices",
      sectionStart: "When it starts",
      sectionButtons: "Buttons",
      sectionShortcuts: "Shortcuts",
      sectionEnd: "When it ends",
      sectionDeviceWide: "Device-wide changes",
      deviceAdded: (name: string) => `Added "${name}" to this activity.`,
      deviceRemoved: (name: string) => `Removed "${name}" from this activity.`,
      inputChanged: (device: string, input: string) => `"${device}" input changed to ${input}.`,
      inputCleared: (device: string) => `"${device}" input cleared.`,
      startReordered: "Start sequence reordered.",
      roleNowControls: (group: string, device: string) => `${group} now control "${device}".`,
      roleCustomized: (group: string) => `${group} customized.`,
      roleCleared: (group: string) => `${group} no longer assigned.`,
      shortcutAdded: (name: string) => `Added "${name}".`,
      shortcutRemoved: (name: string) => `Removed "${name}".`,
      shortcutRenamed: (oldName: string, newName: string) => `Renamed "${oldName}" → "${newName}".`,
      shortcutsReordered: "Reordered shortcuts.",
      idleChanged: (device: string, label: string) => `"${device}" idle behavior → ${label}.`,
      commandRenamed: (oldName: string, newName: string, device: string) =>
        `Renamed command "${oldName}" → "${newName}" on "${device}".`,
      roleGroups: {
        volume: "Volume buttons",
        navigation: "Navigation buttons",
        playback: "Playback buttons",
        channels: "Channel buttons",
      } as Record<string, string>,
      idleShort: {
        0: "not set",
        1: "turns off when idle",
        2: "never switches off",
        3: "stays on",
        4: "not managed by the hub",
      } as Record<number, string>,
    },
    // Review-list section titles + entry templates for the live *device*
    // editor (activity-diff.ts, diffDeviceForReview).
    deviceReview: {
      sectionPower: "Power",
      sectionButtons: "Buttons",
      sectionMacros: "Macros",
      powerControlChanged: (label: string) => `Automatic power control → ${label}.`,
      powerOnChanged: "Power-on sequence updated.",
      powerOffChanged: "Power-off sequence updated.",
      macroAdded: (name: string) => `Added macro "${name}".`,
      macroRemoved: (name: string) => `Removed macro "${name}".`,
      macroRenamed: (oldName: string, newName: string) => `Renamed macro "${oldName}" → "${newName}".`,
      macroChanged: (name: string) => `Edited macro "${name}".`,
      bindingBound: (button: string, command: string) => `"${button}" now sends "${command}".`,
      bindingCleared: (button: string) => `"${button}" no longer bound.`,
    },
  },
  backup: {
    loading: "Loading backup tools...",
    selectHub: "Select a hub to manage backups.",
    creatingSubtitle: "The hub is creating your backup.",
    readySubtitle: "Your backup is ready.",
    chooseSubtitle: "Choose what to include in this backup.",
    enablePersistentCache: "Enable persistent cache to choose backup contents from the card.",
    completedTitle: "Backup completed",
    expired: "Backup expired. Start a new backup to download again.",
    downloaded: "Downloaded",
    downloadAgain: "Download again",
    downloadBackup: "Download backup",
    complete: "Complete",
    entireHub: "Entire hub",
    selectedDevices: "Selected devices",
    devicesToInclude: "Devices to include",
    selectedCount: (count: number) => `${count} selected`,
    deselectAll: "Deselect all",
    selectAll: "Select all",
    noDevicesAvailable: "No devices available.",
    working: "Working",
    startBackup: "Start backup",
    editLoadPrompt: "Load a backup file, then choose an Activity or Device to edit.",
    chooseBackupFile: "Choose backup file",
    reorderHint: " Drag the handle on any row to reorder Activities and Devices.",
    hubName: "Hub name",
    hubNameNotSet: "(not set)",
    renameHub: "Rename Hub",
    activities: "Activities",
    noActivitiesInFile: "This backup file has no activities.",
    devices: "Devices",
    noDevicesInFile: "This backup file has no devices.",
    unsavedChanges: "Unsaved changes. Click ",
    downloadEditedBackupStrong: "Download edited backup",
    unsavedChangesSuffix: " to save them to a file.",
    downloadEditedBackup: "Download edited backup",
    deleteActivityTitle: (name: string) => `Delete activity "${name}"?`,
    deleteDeviceTitle: (name: string) => `Delete device "${name}"?`,
    deleteCommandTitle: (name: string) => `Delete command "${name}"?`,
    deleteFavoriteTitle: (name: string) => `Delete shortcut "${name}"?`,
    deleteMacroTitle: (name: string) => `Delete macro "${name}"?`,
    deleteCascadeIntro: "Removing this also clears its references elsewhere in the backup:",
    deleteSimpleBody: "This removes it from the loaded backup.",
    deleteImpactActivities: (count: number) =>
      `${count} ${count === 1 ? "activity references" : "activities reference"} it`,
    deleteImpactFavorites: (count: number) =>
      `${count} shortcut${count === 1 ? "" : "s"} will be removed`,
    deleteImpactMacroSteps: (count: number) =>
      `${count} sequence step${count === 1 ? "" : "s"} will be removed`,
    deleteReplaceNote: "Deletions reach the hub only with a Replace restore.",
    // Live-edit variants: deletions here act on the hub, not a backup file.
    deleteCascadeIntroLive: "Deleting this also removes its references on the hub:",
    deleteSimpleBodyLive: "This removes it.",
    deleteImmediateNote: "This is applied to the hub immediately.",
    deleteSyncNote: "This change is written to the hub on the next Sync.",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete",
    deleteActivityAria: "Delete activity",
    deleteDeviceAria: "Delete device",
    deleteCommandAria: "Delete command",
    addFavoriteTitle: "Add command shortcut",
    addFavoriteDevice: "Device",
    addFavoriteCommand: "Command",
    addFavoriteName: "Display name",
    addFavoriteAdd: "Add",
    addFavoriteCancel: "Cancel",
    addFavoriteNoDevices: "This backup has no devices with commands to add.",
    addFavoriteNoCommands: "This device has no commands to add.",
    buttonBindingsTitle: "Button bindings",
    buttonBindingsActivitySub: "Bind remote buttons to a device's command within this Activity.",
    buttonBindingsDeviceSub: "Bind remote buttons to this Device's own commands.",
    buttonBindingsEmpty: "No button bindings configured.",
    addBinding: "Add binding",
    bindingButton: "Button",
    bindingTargetDevice: "Device",
    bindingCommand: "Command",
    bindingEnableLongPress: "Enable long-press binding",
    bindingLongPressDevice: "Long-press device",
    bindingLongPressCommand: "Long-press command",
    bindingIncomplete: "Choose a button and target first.",
    bindingNoButtons: "Every button on this hub model is already bound.",
    bindingNoCommands: "This device has no commands to bind.",
    bindingNoDevices: "This backup has no devices with commands to bind.",
    bindingAdd: "Add",
    bindingSave: "Save",
    bindingCancel: "Cancel",
    bindingDialogAddTitle: "Add button binding",
    bindingDialogEditTitle: (name: string) => `Edit ${name} binding`,
    bindingLongPressMeta: (label: string) => `Long press · ${label}`,
    deleteBindingTitle: (name: string) => `Delete ${name} binding?`,
    deleteBindingAria: "Delete binding",
    deleteImpactBindings: (count: number) =>
      `${count} button binding${count === 1 ? "" : "s"} will be cleared`,
    macrosTitle: "Macros",
    macrosDeviceSub: "Edit the command sequences this device plays, including its power on / off.",
    macroPowerChip: "power",
    powerSetupTitle: "Power",
    powerSetupDeviceSub:
      "How the hub manages this device's power for Activities, and the sequences it sends to switch it on and off.",
    powerSetupActivitySub: "The startup and shutdown sequence this Activity runs.",
    powerOnLabel: "Power-on sequence",
    powerOffLabel: "Power-off sequence",
    // Automatic-power dropdown (device only). One hub byte encodes the whole
    // "Power On/Off Setup" + "Idle Behavior" story, so it is one selector here.
    powerControlTitle: "Automatic power control",
    powerControlUnset: "Not captured",
    powerControlUnsetSub:
      "This backup predates power-control capture. Pick an option to set it, or restore as-is to keep the legacy value.",
    powerControlDisabled: "Don't control power",
    powerControlDisabledSub: "The hub never switches this device on or off. The sequences below are ignored.",
    powerControlAutoOff: "Turn off when idle",
    powerControlAutoOffSub: "Recommended. Powers the device off when no Activity needs it.",
    powerControlStayOn: "Stay on between Activities",
    powerControlStayOnSub: "Skips the wait to power back on; still turns off with the remote's Off button.",
    powerControlAlwaysOn: "Always stay on",
    powerControlAlwaysOnSub: "The hub powers it on but never switches it off automatically.",
    powerSequencesDisabledNote:
      "Power control is off, so these sequences aren't used. Switch it on above to edit them.",
    inputStepTitle: "Set input",
    inputStepCommand: "Input command",
    inputStepNone: "— no input —",
    macroStepsCount: (count: number) => `${count} step${count === 1 ? "" : "s"}`,
    noMacroSteps: "No steps yet.",
    addStep: "Add step",
    stepDialogAddTitle: "Add step",
    stepDialogEditTitle: "Edit step",
    stepDevice: "Device",
    stepCommand: "Command",
    stepHoldSeconds: "Hold (seconds, 0 = click)",
    holdLabel: (seconds: string) => `Hold ${seconds}s`,
    stepAdd: "Add",
    stepSave: "Save",
    stepCancel: "Cancel",
    stepNoCommands: "This device has no commands.",
    stepWaitAria: "Wait after this step (seconds)",
    stepWaitLabel: "Delay",
    stepWaitUnit: "s",
    renameMacroAria: "Rename macro",
    deleteStepAria: "Delete step",
    editStepAria: "Edit step",
    newMacroName: "Macro",
    shortcutChipCommand: "command",
    shortcutChipAction: "macro",
    shortcutRenameAria: (kind: "macro" | "favorite") =>
      kind === "macro" ? "Rename macro" : "Rename shortcut",
    shortcutDeleteAria: (kind: "macro" | "favorite") =>
      kind === "macro" ? "Delete macro" : "Delete shortcut",
    powerSectionTitle: "Power",
    powerActivitySub: "Each device the Activity uses powers on here. Pick its input and adjust the timing.",
    powerInputLabel: "Input",
    powerInputNone: "— none —",
    powerDelayLabel: "Delay (s)",
    powerNoDevices: "No devices yet. Add a favorite, binding, or macro that uses one.",
    powerOnSequence: "Power-on sequence",
    powerOffSequence: "Power-off sequence",
    powerSequenceSub: "Reorder steps, add your own commands or waits. Required device steps can be reordered but not removed.",
    macroRenameAria: "Rename macro",
    editStepsAria: "Edit steps",
    crumbActivities: "Activities",
    crumbDevices: "Devices",
    // Activity-detail copy.
    activityRemoveDeviceTitle: (name: string) => `Remove ${name} from this activity?`,
    activityRunningTitle: "Buttons on the remote",
    activityRunningSub: "Which device each remote button controls in this activity.",
    activityShortcutsTitle: "Shortcuts on the remote screen",
    activityShortcutsSubSortable: "Commands and macros shown on the remote's screen. Drag the handle to reorder.",
    activityShortcutsSubStatic: "Commands and macros shown on the remote's screen. Use the move buttons to reorder.",
    activityShortcutsEmpty: "No shortcuts yet. Add a command or a macro.",
    // Role-based button assignment (Phase B).
    roleVolume: "Volume buttons control",
    roleNavigation: "Navigation and OK control",
    rolePlayback: "Playback buttons control",
    roleChannels: "Channel buttons control",
    roleNotUsed: "Not used",
    roleCustom: "Custom",
    roleCustomized: (name: string) => `${name} (customized)`,
    roleMappedNote: (bound: number, total: number) => `${bound} of ${total} buttons mapped`,
    roleOptionNoMapping: (name: string) => `${name} — no button mapping`,
    roleMenuAria: (roleLabel: string) => `Choose a device for: ${roleLabel}`,
    roleConfirmTitle: "Replace custom button setup?",
    roleConfirmBody:
      "This group has button assignments that don't come from a single device's standard mapping. Assigning it here replaces them.",
    roleConfirmReplace: "Replace",
    roleConfirmCancel: "Cancel",
    customizeButtonsToggle: "Customize individual buttons",
    bindingsViewTitle: "Individual buttons",
    bindingsConfiguredCount: (count: number) => `${count} configured`,
    bindingsNoneConfigured: "None customized",
    // Unified "add to shortcuts" flow.
    addShortcutButton: "Add",
    addShortcutTitle: "Add to shortcuts",
    addShortcutKindLabel: "Type",
    shortcutKindCommand: "Device command",
    shortcutKindAction: "Macro",
    macroTargetLabel: "Macro",
    macroTargetCreateNew: "Create new macro",
    macroTargetNoExisting: "No macros yet. Create one below.",
    addShortcutActionName: "Name",
    addShortcutActionHelper: "You'll pick the steps next.",
  },
  wifiCommands: {
    docsUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/wifi_commands.md",
    sectionLabel: "Wifi Devices",
    deployingTitle: "Deploying Wifi Commands",
    sectionSubtitle: "Choose a Wifi Device to edit its command slots, or add a new one.",
    addDevice: "Add Wifi Device",
    syncingDeviceFallback: "Syncing Wifi Device...",
    syncingDeviceNamed: (deviceName: string) => `Syncing ${deviceName}...`,
    syncInProgress: "Sync in progress",
    startSync: "Starting sync",
    syncFailedToStart: "Sync failed to start",
    syncMessageRemoteUnavailable: "Remote entity unavailable. Is the app connected?",
    syncMessageFailed: "Last sync failed.",
    syncMessageNeeded: "Command config changes need to be synced to the hub.",
    syncMessageUpToDate: "Hub command configuration is up to date.",
    syncMessageIdle: "No sync needed.",
    syncShortUnavailable: "Unavailable",
    syncShortRunning: "Syncing",
    syncShortFailed: "Sync failed",
    syncShortNeeded: "Sync needed",
    syncShortUpToDate: "Up to date",
    syncShortIdle: "Idle",
    deviceDeleting: "Deleting...",
    deviceSynced: "Synced",
    seeDocumentation: "See documentation",
    actionButtonUnavailable: "Unavailable",
    actionButtonSyncing: "Syncing...",
    actionButtonBusy: "Busy",
    actionButtonSyncToHub: "Sync to Hub",
    actionButtonUpToDate: "Up to Date",
    createDeviceBusy: "Creating Wifi Device...",
    createDeviceNameRequired: "Device name is required.",
    createDeviceFailed: "Unable to create Wifi Device",
    deleteDeviceBusy: "Deleting Wifi Device...",
    deleteDeviceFailed: "Unable to delete Wifi Device",
    createModalCancel: "Cancel",
    createModalCreate: "Create",
    deleteModalTitle: "Delete Wifi Device?",
    deleteModalBody: (deviceName: string) => `Delete "${deviceName}" from the hub and remove its saved command-slot configuration?`,
    deleteModalDelete: "Delete",
    clearSlotTitle: "Clear command slot?",
    clearSlotSubtitle: "Resets configuration.",
    clearSlotNo: "No",
    clearSlotYes: "Yes",
    makeCommand: "Make Command",
    noActionConfigured: "No Action configured",
    commandSlotTitle: (slotIndex: number) => `Command Slot ${slotIndex + 1}`,
    commandSlotActionTitle: (slotIndex: number) => `Command Slot ${slotIndex + 1} Action`,
    commandDisplayName: "Command Display Name",
    advanced: "Advanced",
    powerOn: "Set as Power ON command",
    powerOff: "Set as Power OFF command",
    activityInput: "Set as Activity input",
    noActivitiesForHub: "No Activities available for this hub.",
    activityInputLabel: "Activity to apply the input to",
    favorite: "Set as Favorite",
    physicalButtonAssignment: "Physical Button Assignment",
    enableLongPress: "Enable long-press",
    applyToActivities: "Apply to these Activities",
    actionModalNote:
      "Run an Action whenever the command is performed. Configuring an Action is optional; you can create your own automations that trigger from the Wifi Commands sensor.",
    shortPress: "Short press",
    longPress: "Long press",
    selectLongPressAction: "Select Long-Press Action",
    selectTriggeredAction: "Select Triggered Action",
    action: "Action",
    save: "Save",
    syncWarningTitle: "Sync commands to hub?",
    syncWarningBody:
      "This sync can run for several minutes. During this process, other interactions with the hub are blocked.",
    syncWarningBody2:
      "At the end of deployment, the physical remote will be force-resynced. It is recommended to finish your full Wifi Commands setup first, then sync once.",
    syncWarningOptOut: "Don't show this warning again for this remote.",
    syncWarningStart: "Start sync",
    keyLabels: {
      up: "Up",
      down: "Down",
      left: "Left",
      right: "Right",
      ok: "OK",
      back: "Back",
      home: "Home",
      menu: "Menu",
      volup: "Vol +",
      voldn: "Vol -",
      mute: "Mute",
      chup: "Ch +",
      chdn: "Ch -",
      guide: "Guide",
      dvr: "DVR",
      play: "Play",
      exit: "Exit",
      rew: "Rewind",
      pause: "Pause",
      fwd: "Fast Forward",
      red: "Red",
      green: "Green",
      yellow: "Yellow",
      blue: "Blue",
      a: "A",
      b: "B",
      c: "C",
    } as Record<string, string>,
  },
} as const;
