import type { BlobsSectionId, TabId } from "./shared/ha-context";

export const TOOLS_CARD_STRINGS = {
  docs: {
    wifiCommandsUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/wifi_commands.md",
    backupUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/backup.md",
    blobsUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/blobs.md",
  },
  tabs: {
    cache: "Cache",
    wifiCommands: "Wifi Commands",
    wifiShort: "Wifi",
    backup: "Backup",
    blobs: "Blobs",
    settings: "Settings",
    logs: "Logs",
  },
  tabDocs: {
    wifi_commands: "Wifi Commands documentation",
    backup: "Backup documentation",
    blobs: "Blobs documentation",
  } satisfies Partial<Record<TabId, string>>,
  backend: {
    unavailableTitle: "Backend not available",
    unavailableCopy: "Waiting for the Sofabaton X integration to finish starting...",
    versionMismatchTitle: "Refresh required to update the Sofabaton Control Panel card",
    versionMismatchCopy:
      "This dashboard is still using an older cached version of the Sofabaton Control Panel card than the one now running in Home Assistant. Refresh or reopen the dashboard/browser before using the control panel again so the updated card can load.",
    backendExpects: "Backend expects",
    cardLoaded: "Card loaded",
    unknownVersion: "unknown",
    refreshingCache: "Refreshing cache...",
    hubCommandInProgress: "Hub command in progress...",
  },
  hubUnavailable: {
    title: "Hub unavailable",
    copy: "This hub is not connected, so the control panel is unavailable until the hub reconnects.",
  },
  settings: {
    loading: "Loading...",
    noHubsFound: "No hubs found.",
    unknownHubName: "Unknown",
    activities: "Activities",
    devices: "Devices",
    persistentCacheTitle: "Persistent Cache",
    persistentCacheDescription: "Store activity and device data locally for faster access.",
    persistentCacheFooter: "GLOBAL",
    hexLoggingTitle: "Hex Logging",
    hexLoggingDescription: "Log raw hex traffic between hub, integration, and app.",
    proxyTitle: "Proxy",
    proxyDescription: "Let the official Sofabaton app share the hub connection with HA simultaneously.",
    wifiDeviceTitle: "WiFi Device",
    wifiDeviceDescription: "Enable the HTTP listener that captures remote button presses and routes them to HA actions.",
    findRemoteTitle: "Find Remote",
    findRemoteDescription: "Make the remote beep so you can locate it.",
    syncRemoteTitle: "Sync Remote",
    syncRemoteDescription: "Push the latest configuration to the physical remote.",
  },
  cache: {
    loading: "Loading...",
    noHubsFound: "No hubs found.",
    persistentCacheOffTitle: "Persistent cache is off",
    persistentCacheOffCopy:
      "Turn it on to browse cached activities and devices, and to unlock Backup and Blobs workflows that depend on it.",
    enablingPersistentCache: "Enabling...",
    enablePersistentCache: "Enable persistent cache",
    devIdBadge: "DevID",
    favIdBadge: "FavID",
    comIdBadge: "ComID",
    activityFallback: (id: number) => `Activity ${id}`,
    deviceFallback: (id: number) => `Device ${id}`,
    favoriteFallback: (commandId: number) => `Favorite ${commandId}`,
    macroFallback: (commandId: number) => `Macro ${commandId}`,
    activityCounts: (favorites: number, macros: number, buttons: number) =>
      `${favorites} favs / ${macros} macros / ${buttons} btns`,
    deviceCommandCount: (count: number) => `${count} cmds`,
    favorites: "Favorites",
    macros: "Macros",
    buttons: "Buttons",
    noCachedData: "No cached data yet.",
    noCachedCommands: "No cached commands.",
    staleBanner: "Cache was updated externally. Refresh to see latest data.",
    refresh: "Refresh",
    activities: "Activities",
    devices: "Devices",
    refreshList: "Refresh list",
  },
  logs: {
    loading: "Loading log stream...",
    empty: "No log lines captured for this hub yet.",
    liveConsole: "Live Console",
  },
  progress: {
    homeAssistant: "Home Assistant",
    sofabatonHub: "Sofabaton Hub",
    working: "Working...",
    backupTitle: "Creating backup",
    restoreTitle: "Restoring backup",
  },
  blobs: {
    loading: "Loading...",
    noHubsFound: "No hubs found.",
    sections: {
      fetch: "Fetch",
      test: "Test",
      save: "Save",
    } satisfies Record<BlobsSectionId, string>,
    fetchCacheDisabled: "Enable persistent cache in the Hub tab before using Fetch.",
    selectOne: "Select one",
    device: "Device",
    command: "Command",
    fetchNoCommands: "This device has no cached commands yet. Refresh that device from the Cache tab first.",
    fetchNoRecords: "The hub returned no blob records for this request.",
    commandFallback: (commandId: string | number) => `Command ${commandId}`,
    unknown: "unknown",
    cmdBadge: (commandId: string | number) => `Cmd ${commandId}`,
    blobViewMode: "Blob view mode",
    descriptor: "Descriptor",
    hex: "Hex",
    rawBlob: "Raw Blob",
    copied: "Copied",
    copy: "Copy",
    test: "Test",
    testing: "Testing...",
    noIrDevices: "No IR devices found in the cache. Refresh devices from the Cache tab first.",
    irDevice: "IR device",
    save: "Save",
    saving: "Saving...",
    commandName: "Command name",
  },
  backup: {
    loading: "Loading backup tools...",
    selectHub: "Select a hub to manage backups.",
    creatingSubtitle: "The hub is creating your backup.",
    readySubtitle: "Your backup is ready.",
    chooseSubtitle: "Choose what to include in this backup.",
    enablePersistentCache: "Enable persistent cache to choose backup contents from the card.",
    completedTitle: "Backup completed",
    expired: "Backup expired. Start a new backup to download again.",
    downloaded: "Downloaded",
    downloadAgain: "Download again",
    downloadBackup: "Download backup",
    complete: "Complete",
    entireHub: "Entire hub",
    selectedDevices: "Selected devices",
    devicesToInclude: "Devices to include",
    selectedCount: (count: number) => `${count} selected`,
    deselectAll: "Deselect all",
    selectAll: "Select all",
    noDevicesAvailable: "No devices available.",
    working: "Working",
    startBackup: "Start backup",
    editLoadPrompt: "Load a backup file, then choose an Activity or Device to edit.",
    chooseBackupFile: "Choose backup file",
    reorderHint: " Drag the handle on any row to reorder Activities and Devices.",
    hubName: "Hub name",
    hubNameNotSet: "(not set)",
    renameHub: "Rename Hub",
    activities: "Activities",
    noActivitiesInFile: "This backup file has no activities.",
    devices: "Devices",
    noDevicesInFile: "This backup file has no devices.",
    unsavedChanges: "Unsaved changes. Click ",
    downloadEditedBackupStrong: "Download edited backup",
    unsavedChangesSuffix: " to save them to a file.",
    downloadEditedBackup: "Download edited backup",
    deleteActivityTitle: (name: string) => `Delete activity "${name}"?`,
    deleteDeviceTitle: (name: string) => `Delete device "${name}"?`,
    deleteCommandTitle: (name: string) => `Delete command "${name}"?`,
    deleteFavoriteTitle: (name: string) => `Delete shortcut "${name}"?`,
    deleteMacroTitle: (name: string) => `Delete custom action "${name}"?`,
    deleteCascadeIntro: "Removing this also clears its references elsewhere in the backup:",
    deleteSimpleBody: "This removes it from the loaded backup.",
    deleteImpactActivities: (count: number) =>
      `${count} ${count === 1 ? "activity references" : "activities reference"} it`,
    deleteImpactFavorites: (count: number) =>
      `${count} shortcut${count === 1 ? "" : "s"} will be removed`,
    deleteImpactMacroSteps: (count: number) =>
      `${count} sequence step${count === 1 ? "" : "s"} will be removed`,
    deleteReplaceNote: "Deletions reach the hub only with a Replace restore.",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete",
    deleteActivityAria: "Delete activity",
    deleteDeviceAria: "Delete device",
    deleteCommandAria: "Delete command",
    addFavoriteTitle: "Add command shortcut",
    addFavoriteDevice: "Device",
    addFavoriteCommand: "Command",
    addFavoriteName: "Display name",
    addFavoriteAdd: "Add",
    addFavoriteCancel: "Cancel",
    addFavoriteNoDevices: "This backup has no devices with commands to add.",
    addFavoriteNoCommands: "This device has no commands to add.",
    buttonBindingsTitle: "Button bindings",
    buttonBindingsActivitySub: "Bind remote buttons to a device's command within this Activity.",
    buttonBindingsDeviceSub: "Bind remote buttons to this Device's own commands.",
    buttonBindingsEmpty: "No button bindings configured.",
    addBinding: "Add binding",
    bindingButton: "Button",
    bindingTargetDevice: "Device",
    bindingMacroTarget: "This activity · macros",
    bindingCommand: "Command",
    bindingEnableLongPress: "Enable long-press binding",
    bindingLongPressDevice: "Long-press device",
    bindingLongPressCommand: "Long-press command",
    bindingIncomplete: "Choose a button and command first.",
    bindingNoButtons: "Every button on this hub model is already bound.",
    bindingNoCommands: "This device has no commands to bind.",
    bindingNoDevices: "This backup has no devices with commands to bind.",
    bindingAdd: "Add",
    bindingSave: "Save",
    bindingCancel: "Cancel",
    bindingDialogAddTitle: "Add button binding",
    bindingDialogEditTitle: (name: string) => `Edit ${name} binding`,
    bindingLongPressMeta: (label: string) => `Long press · ${label}`,
    deleteBindingTitle: (name: string) => `Delete ${name} binding?`,
    deleteBindingAria: "Delete binding",
    deleteImpactBindings: (count: number) =>
      `${count} button binding${count === 1 ? "" : "s"} will be cleared`,
    macrosTitle: "Macros",
    macrosDeviceSub: "Edit the command sequences this device plays, including its power on / off.",
    macroPowerChip: "power",
    powerSetupTitle: "Power",
    powerSetupDeviceSub:
      "How the hub manages this device's power for Activities, and the sequences it sends to switch it on and off.",
    powerSetupActivitySub: "The startup and shutdown sequence this Activity runs.",
    powerOnLabel: "Power-on sequence",
    powerOffLabel: "Power-off sequence",
    // Automatic-power dropdown (device only). One hub byte encodes the whole
    // "Power On/Off Setup" + "Idle Behavior" story, so it is one selector here.
    powerControlTitle: "Automatic power control",
    powerControlUnset: "Not captured",
    powerControlUnsetSub:
      "This backup predates power-control capture. Pick an option to set it, or restore as-is to keep the legacy value.",
    powerControlDisabled: "Don't control power",
    powerControlDisabledSub: "The hub never switches this device on or off. The sequences below are ignored.",
    powerControlAutoOff: "Turn off when idle",
    powerControlAutoOffSub: "Recommended. Powers the device off when no Activity needs it.",
    powerControlStayOn: "Stay on between Activities",
    powerControlStayOnSub: "Skips the wait to power back on; still turns off with the remote's Off button.",
    powerControlAlwaysOn: "Always stay on",
    powerControlAlwaysOnSub: "The hub powers it on but never switches it off automatically.",
    powerSequencesDisabledNote:
      "Power control is off, so these sequences aren't used. Switch it on above to edit them.",
    inputStepTitle: "Set input",
    inputStepCommand: "Input command",
    inputStepNone: "— no input —",
    macroStepsCount: (count: number) => `${count} step${count === 1 ? "" : "s"}`,
    noMacroSteps: "No steps yet.",
    addStep: "Add step",
    stepDialogAddTitle: "Add step",
    stepDialogEditTitle: "Edit step",
    stepDevice: "Device",
    stepCommand: "Command",
    stepHoldSeconds: "Hold (seconds, 0 = click)",
    holdLabel: (seconds: string) => `Hold ${seconds}s`,
    stepAdd: "Add",
    stepSave: "Save",
    stepCancel: "Cancel",
    stepNoCommands: "This device has no commands.",
    stepWaitAria: "Wait after this step (seconds)",
    stepWaitLabel: "Delay",
    stepWaitUnit: "s",
    renameMacroAria: "Rename macro",
    deleteStepAria: "Delete step",
    editStepAria: "Edit step",
    newMacroName: "Custom action",
    shortcutChipCommand: "command",
    shortcutChipAction: "custom action",
    shortcutRenameAria: (kind: "macro" | "favorite") =>
      kind === "macro" ? "Rename custom action" : "Rename shortcut",
    shortcutDeleteAria: (kind: "macro" | "favorite") =>
      kind === "macro" ? "Delete custom action" : "Delete shortcut",
    powerSectionTitle: "Power",
    powerActivitySub: "Each device the Activity uses powers on here. Pick its input and adjust the timing.",
    powerInputLabel: "Input",
    powerInputNone: "— none —",
    powerDelayLabel: "Delay (s)",
    powerNoDevices: "No devices yet. Add a favorite, binding, or macro that uses one.",
    powerOnSequence: "Power-on sequence",
    powerOffSequence: "Power-off sequence",
    powerSequenceSub: "Reorder steps, add your own commands or waits. Required device steps can be reordered but not removed.",
    macroRenameAria: "Rename macro",
    editStepsAria: "Edit steps",
    crumbActivities: "Activities",
    crumbDevices: "Devices",
    // Narrative activity editor (docs/internal/activity-editor-plan.md).
    // Section headings tell the activity's story in order: devices →
    // start → running → shortcuts → end. Storage vocabulary (macro,
    // binding, favorite slot) stays out of the copy.
    activityDevicesTitle: "Devices in this activity",
    activityDevicesSub: "Everything below follows from this list.",
    activityDevicesEmpty: "No devices yet. Add one to get started.",
    activityAddDevice: "Add device",
    activityAddDeviceNone: "Every device in this backup is already part of this activity.",
    activityRemoveDeviceAria: (name: string) => `Remove ${name} from this activity`,
    activityRemoveDeviceTitle: (name: string) => `Remove ${name} from this activity?`,
    activityStartTitle: "When the activity starts",
    activityStartSub: "What each device does when this activity begins.",
    activityStartTurnsOn: "Turns on",
    activityStartStaysAsIs: "Stays as is",
    activityStartToggleAria: (name: string) => `Toggle whether ${name} turns on`,
    activityStartInputLabel: "Input",
    activityStartInputNone: "— none —",
    activityStartInputAria: (name: string) => `Input for ${name}`,
    activityStartSequenceTitle: "Start sequence",
    activityEndSequenceTitle: "End sequence",
    activityRunningTitle: "While the activity is running",
    activityRunningSub: "Which device each remote button controls in this activity.",
    activityShortcutsTitle: "Shortcuts on the remote screen",
    activityShortcutsSubSortable: "Commands and custom actions shown on the remote's screen. Drag the handle to reorder.",
    activityShortcutsSubStatic: "Commands and custom actions shown on the remote's screen. Use the move buttons to reorder.",
    activityShortcutsEmpty: "No shortcuts yet. Add a command or a custom action.",
    activityEndTitle: "When the activity ends",
    activityEndSub: "What each device does when this activity is switched off.",
    activityEndTurnsOff: "Turns off",
    activityEndStaysOn: "Stays on",
    activityEndToggleAria: (name: string) => `Toggle whether ${name} turns off`,
    // Per-device automatic power (device-level idle behavior, 0x0242).
    // Activity switches are governed by THIS, not the activity macros.
    activityIdleAutoOff: "Between activities: turns off when not needed",
    activityIdleStayOn: "Between activities: stays on",
    activityIdleAlwaysOn: "Between activities: never switched off",
    activityIdleDisabled: "Power not managed by the hub",
    activityIdleUnset: "Automatic power: not set",
    activityIdleAria: (name: string) => `Change automatic power for ${name}`,
    activityIdleMenuNote: "Applies to the device in every activity.",
    activitySectionDevices: "Devices",
    activitySectionStart: "Start",
    activitySectionRunning: "Buttons",
    activitySectionShortcuts: "Shortcuts",
    activitySectionEnd: "End",
    // Role-based button assignment (Phase B).
    roleVolume: "Volume buttons control",
    roleNavigation: "Navigation and OK control",
    rolePlayback: "Playback buttons control",
    roleChannels: "Channel buttons control",
    roleNotUsed: "Not used",
    roleCustom: "Custom",
    roleCustomized: (name: string) => `${name} (customized)`,
    roleMappedNote: (bound: number, total: number) => `${bound} of ${total} buttons mapped`,
    roleOptionNoMapping: (name: string) => `${name} — no button mapping`,
    roleMenuAria: (roleLabel: string) => `Choose a device for: ${roleLabel}`,
    roleConfirmTitle: "Replace custom button setup?",
    roleConfirmBody:
      "This group has button assignments that don't come from a single device's standard mapping. Assigning it here replaces them.",
    roleConfirmReplace: "Replace",
    roleConfirmCancel: "Cancel",
    customizeButtonsToggle: "Customize individual buttons",
    bindingsViewTitle: "Individual buttons",
    bindingsConfiguredCount: (count: number) => `${count} configured`,
    bindingsNoneConfigured: "None customized",
    sequenceRowLabel: "Adjust order, delays, and extra steps",
    // Unified "add to shortcuts" flow.
    addShortcutButton: "Add",
    addShortcutTitle: "Add to shortcuts",
    addShortcutKindLabel: "Type",
    shortcutKindCommand: "Device command",
    shortcutKindAction: "Custom action",
    shortcutKindHa: "Home Assistant action",
    addShortcutActionName: "Name",
    addShortcutActionHelper: "You'll pick the steps next.",
    // Home Assistant actions (Phase D).
    haActionDialogTitle: "Add Home Assistant action",
    haActionNameLabel: "Name",
    haActionNameHelper: "Shown on the remote; Home Assistant receives it when the shortcut is pressed.",
    haActionAddressLabel: "Home Assistant address",
    haActionAddressHelper:
      "IPv4 address (and optional :port) where the hub can reach this Home Assistant on your network. The wifi-commands listener answers there.",
    haActionNameRequired: "Enter a name.",
    haActionInvalidAddress: "Enter the address as IPv4 or IPv4:port, e.g. 192.168.1.10:8060.",
    haActionNoSlots: "No free slots — the shared device-id space is full.",
    haActionAdd: "Add",
    haActionCancel: "Cancel",
    haActionChip: "HA action",
  },
  wifiCommands: {
    docsUrl: "https://github.com/m3tac0de/home-assistant-sofabaton-x1s/blob/main/docs/wifi_commands.md",
    sectionLabel: "Wifi Devices",
    deployingTitle: "Deploying Wifi Commands",
    sectionSubtitle: "Choose a Wifi Device to edit its command slots, or add a new one.",
    addDevice: "Add Wifi Device",
    syncingDeviceFallback: "Syncing Wifi Device...",
    syncingDeviceNamed: (deviceName: string) => `Syncing ${deviceName}...`,
    syncInProgress: "Sync in progress",
    startSync: "Starting sync",
    syncFailedToStart: "Sync failed to start",
    syncMessageRemoteUnavailable: "Remote entity unavailable. Is the app connected?",
    syncMessageFailed: "Last sync failed.",
    syncMessageNeeded: "Command config changes need to be synced to the hub.",
    syncMessageUpToDate: "Hub command configuration is up to date.",
    syncMessageIdle: "No sync needed.",
    syncShortUnavailable: "Unavailable",
    syncShortRunning: "Syncing",
    syncShortFailed: "Sync failed",
    syncShortNeeded: "Sync needed",
    syncShortUpToDate: "Up to date",
    syncShortIdle: "Idle",
    deviceDeleting: "Deleting...",
    deviceSynced: "Synced",
    seeDocumentation: "See documentation",
    actionButtonUnavailable: "Unavailable",
    actionButtonSyncing: "Syncing...",
    actionButtonBusy: "Busy",
    actionButtonSyncToHub: "Sync to Hub",
    actionButtonUpToDate: "Up to Date",
    createDeviceBusy: "Creating Wifi Device...",
    createDeviceNameRequired: "Device name is required.",
    createDeviceFailed: "Unable to create Wifi Device",
    deleteDeviceBusy: "Deleting Wifi Device...",
    deleteDeviceFailed: "Unable to delete Wifi Device",
    createModalCancel: "Cancel",
    createModalCreate: "Create",
    deleteModalTitle: "Delete Wifi Device?",
    deleteModalBody: (deviceName: string) => `Delete "${deviceName}" from the hub and remove its saved command-slot configuration?`,
    deleteModalDelete: "Delete",
    clearSlotTitle: "Clear command slot?",
    clearSlotSubtitle: "Resets configuration.",
    clearSlotNo: "No",
    clearSlotYes: "Yes",
    makeCommand: "Make Command",
    noActionConfigured: "No Action configured",
    commandSlotTitle: (slotIndex: number) => `Command Slot ${slotIndex + 1}`,
    commandSlotActionTitle: (slotIndex: number) => `Command Slot ${slotIndex + 1} Action`,
    commandDisplayName: "Command Display Name",
    advanced: "Advanced",
    powerOn: "Set as Power ON command",
    powerOff: "Set as Power OFF command",
    activityInput: "Set as Activity input",
    noActivitiesForHub: "No Activities available for this hub.",
    activityInputLabel: "Activity to apply the input to",
    favorite: "Set as Favorite",
    physicalButtonAssignment: "Physical Button Assignment",
    enableLongPress: "Enable long-press",
    applyToActivities: "Apply to these Activities",
    actionModalNote:
      "Run an Action whenever the command is performed. Configuring an Action is optional; you can create your own automations that trigger from the Wifi Commands sensor.",
    shortPress: "Short press",
    longPress: "Long press",
    selectLongPressAction: "Select Long-Press Action",
    selectTriggeredAction: "Select Triggered Action",
    action: "Action",
    save: "Save",
    syncWarningTitle: "Sync commands to hub?",
    syncWarningBody:
      "This sync can run for several minutes. During this process, other interactions with the hub are blocked.",
    syncWarningBody2:
      "At the end of deployment, the physical remote will be force-resynced. It is recommended to finish your full Wifi Commands setup first, then sync once.",
    syncWarningOptOut: "Don't show this warning again for this remote.",
    syncWarningStart: "Start sync",
    keyLabels: {
      up: "Up",
      down: "Down",
      left: "Left",
      right: "Right",
      ok: "OK",
      back: "Back",
      home: "Home",
      menu: "Menu",
      volup: "Vol +",
      voldn: "Vol -",
      mute: "Mute",
      chup: "Ch +",
      chdn: "Ch -",
      guide: "Guide",
      dvr: "DVR",
      play: "Play",
      exit: "Exit",
      rew: "Rewind",
      pause: "Pause",
      fwd: "Fast Forward",
      red: "Red",
      green: "Green",
      yellow: "Yellow",
      blue: "Blue",
      a: "A",
      b: "B",
      c: "C",
    } as Record<string, string>,
  },
} as const;
