name: Bug report
description: Report an issue with the Sofabaton X1/X1S Home Assistant integration
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the integration. Please complete all required fields and attach logs/diagnostics so we can troubleshoot quickly.
  - type: dropdown
    id: hub_model
    attributes:
      label: Hub model
      description: Select the hub model you are using.
      options:
        - X1
        - X1S
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction steps
      description: Provide numbered steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: checkboxes
    id: logging_checklist
    attributes:
      label: Logging requirements
      description: Enable detailed logging before reproducing the issue.
      options:
        - label: I enabled `switch.<hub>_hex_logging` on the hub device.
          required: true
        - label: I downloaded the diagnostics log file.
          required: true
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or diagnostics
      placeholder: |
        1. In Home Assistant, open **Settings → Devices & services**.
        2. Select **Sofabaton X1/X1S** and open the hub device.
        3. Toggle `switch.<hub>_hex_logging` **on** to capture full hub traffic.
        4. Perform the actions that demonstrate the issue while hex logging is enabled.
        5. With hex logging still on, open the **⋮** menu (three dots) on the **Sofabaton X1/X1S** integration card and choose **Download diagnostics**. This downloads the log file we need along with structured diagnostics.
        6. Toggle `switch.<hub>_hex_logging` **off** when finished to reduce noise.
  - type: markdown
    attributes:
      value: |
        Need help enabling logging? See the [logging guide](../../docs/logging.md).
